### ISSUE TITLE
Does not work in Safari

### ISSUE THREAD

**Issue by avaranovich** [RReverser/mpegts#1]
Do you see any particular reason why it doesn't work in safari?

I did some debugging, and my feeling is that after this code is called

``` javascript
(function canplaythrough() {
    console.log('converted ' + descriptor);
    videos[data.index] = this;
    if ((!currentVideo || currentVideo.ended) && data.index === nextIndex) {
        this.play();
    }
}).call(video);
```

"play" event is not triggered, that't is, this callback is never called

``` javascript
video.addEventListener('play', function () {
```

must be some obvious issue, since the video is actually converted.

**Comment by RReverser** [comment]
I've heard about this issue before and suspect that Safari maybe doesn't play video from dynamic Blob URLs, but 1) I can't debug and check this since don't have and can't install Safari on my Windows machine and 2) Safari is actually the only (?) browser that supports HLS natively on all the platforms, so this isn't worth time since convert+play approach isn't efficient there.
