### ISSUE TITLE
Video is small in Firefox (OS)

### ISSUE THREAD

**Issue by Gagaro** [RReverser/mpegts#14]
I'll continue here the discussion about the Firefox bug that we started in #12 .

Video is very small on my FF OS browser (2.1).

It worked fine for me on FF desktop 35 on Windows.

It doesn't work for @RReverser on Developer Edition 37.0a2.

I tested it on the same version (37.0a2) on Xubuntu, and it works for me.

![ff-dev](https://cloud.githubusercontent.com/assets/3845486/6367318/da14ffec-bcd1-11e4-9ec9-1f60d1681c8f.png)

What distribution are you using ?

**Comment by RReverser** [comment]
It's Windows, 37.0a2:

![screenshot-rreverser github io 2015-02-25 11-01-46](https://cloud.githubusercontent.com/assets/557590/6367613/d6a87dfa-bcdd-11e4-8137-346578e35b2e.png)

**Comment by RReverser** [comment]
@Gagaro Any ideas on it?

**Comment by Gagaro** [comment]
Sorry, I didn't really looked at it yet. It's still on my todo list though.

**Comment by gliese1337** [comment]
It's an off-by-one error in the SPS parser. You start reading SPS data one byte off from the right spot, so it produces junk values for the height and width of the video. Chrome ignores the height and width that you put in when decoding an MP4 file, and recovers the proper dimensions from the raw SPS blob. Firefox, on the other hand, seems to ignore the SPS blob and uses the dimensions you provide.

I know this because I wrote my own SPS parser for https://github.com/gliese1337/HLS.js/
If I start it off-by-one, I get identical output to your SPS parser.

**Comment by RReverser** [comment]
@gliese1337 Cool to know, thanks!

**Comment by naktinis** [comment]
Problem still there. So is this a bug in Firefox or in mpegts?

**Comment by RReverser** [comment]
This should be fixed now.
