### ISSUE TITLE
Feedback: Installation instructions

### ISSUE THREAD

**Issue by kaihendry** [RReverser/mpegts#21]
I have a feed, say at http://116.14.203.131/playlist.m3u8 that I would like to use this on. You don't see to provide instructions to do that.

Sidenote: Couldn't I just have a job in my server that converts the mpegts files to proper MP4 files for playback to save work in the browser?

**Comment by cadesalaberry** [comment]
You should have a look at http://rreverser.github.io/mpegts/

Try and replace the `data-hls=` field [line 36](https://github.com/RReverser/mpegts/blob/gh-pages/index.html#L36) with your URL in the web inspector.

**Comment by ralyodio** [comment]
All I need to include is `browser.js` for this to work?

I can't include a script tag in my template file (I'm using single page app framework, and that's just not how things work these days).

I can load `browser.js` via a script tag in my index.html, but how do I get access to the player object? I would need for it to be a global I can use in my controller.

Can I use a video tag? Please provide more real world examples :)

**Comment by RReverser** [comment]
There is no such thing as "player object" here - you can see how play/pause works at these lines: https://github.com/RReverser/mpegts/blob/gh-pages/index.html#L36-L49 (those are the methods tracked on `this.currentVideo.play` / `this.currentVideo.pause` and handled specifically).

Note that this is self-contained stream player demo that is not intended to work as a library (since converting it to such requires dedicated time and efforts).
