### ISSUE TITLE
mp4 to mpegts

### ISSUE THREAD

**Issue by krzysztofantczak** [RReverser/mpegts#7]
Hey,

Would it be hard to implement conversion in opposite direction? from mp4 to mpegts using Your code base? I'm pretty new with video stuff so to be honest i'm not sure where to start with it but i like the idea of container conversion 'on the fly'.

**Comment by RReverser** [comment]
It's possible, but I don't see any benefits of such conversion since browser support MP4 and not MPEGTS. If you want to do this, you should go to https://github.com/RReverser/mpegts/tree/gh-pages/mpegts-to-mp4 and find custom types (`jBinary.Type(...)` and `jBinary.Template(...)`) which are missing `write` method and implement it accordingly to reading. Then you need to write opposite of https://github.com/RReverser/mpegts/blob/gh-pages/mpegts-to-mp4/worker.js.

All this would take time for sure :) I can help you with any questions on jBinary or resources to read.

**Comment by krzysztofantczak** [comment]
Well, right... there is no point to keep .ts files, but i have few use cases where ts files are better fit (m3u8 support on file chunk level) and converting them on-the-fly would be awesome since it's really fast process + it spares a lot of disk space. I'll try to go with Your tips and for sure it will take some time since i've never touched binary data before. Thanks for quick answer ;-)

**Comment by RReverser** [comment]
I'll be happy to help with any questions, but have to warn that it's serious challenge (at least, was for me). But I was developing jBinary in parallel, and most of data structures could be reused, so may be somewhat more easy for you to create back-converter.

Good luck!
